export const questions_api = [
    {
        questionNumber: '1',
        question: 'When filling out the order form, please _____ your address clearly to prevent delays.',
        options: ['A. fix', 'B. write', 'C. send', 'D. direct'],
        correct_answer: 'B. write',
    },
    {
        questionNumber: '2',
        question: 'Ms. Morgan recruited the individuals that the company _____ for the next three months.',
        options: ['A. will employ', 'B. to employ', 'C. has been employed', 'D. employ'],
        correct_answer: 'A. will employ',
    },
    {
        questionNumber: '3',
        question:
            'The contractor had a fifteen-percent _____ in his business after advertising in the local newspaper.',
        options: ['A. experience', 'B. growth', 'C. formula', 'D. incentive'],
        correct_answer: 'B. growth',
    },
    {
        questionNumber: '4',
        question: 'The free clinic was founded by a group of doctors to give _____ for various medical conditions.',
        options: ['A. treatment', 'B. treat', 'C. treated', 'D. treating'],
        correct_answer: 'A. treatment',
    },
    {
        questionNumber: '5',
        question: 'Participants in the walking tour should gather _____ 533 Bates Road on Saturday morning.',
        options: ['A. with', 'B. at', 'C. like', 'D. among'],
        correct_answer: 'B. at',
    },
    {
        questionNumber: '6',
        question: 'The artist sent _____ best pieces to the gallery to be reviewed by the owner.',
        options: ['A. him', 'B. himself', 'C. his', 'D. he'],
        correct_answer: 'C. his',
    },
    {
        questionNumber: '7',
        question: 'The figures that accompany the financial statement should be _____ to the spending category.',
        options: ['A. relevance', 'B. relevantly', 'C. more relevantly', 'D. relevant'],
        correct_answer: 'D. relevant',
    },
    {
        questionNumber: '8',
        question:
            'The building owner purchased the property _____ three months ago, but she has already spent a great deal of money on renovations.',
        options: ['A. yet', 'B. just', 'C. few', 'D. still'],
        correct_answer: 'B. just',
    },
    {
        questionNumber: '9',
        question: 'We would like to discuss this problem honestly and _____ at the next staff meeting.',
        options: ['A. rarely', 'B. tiredly', 'C. openly', 'D. highly'],
        correct_answer: 'C. openly',
    },
    {
        questionNumber: '10',
        question:
            "The store's manager plans to put the new merchandise on display _____ to promote the line of fall fashions.",
        options: ['A. soon', 'B. very', 'C. that', 'D. still'],
        correct_answer: 'A. soon',
    },
    {
        questionNumber: '11',
        question: 'During the peak season, it is _____ to hire additional workers for the weekend shifts.',
        options: ['A. necessitate', 'B. necessarily', 'C. necessary', 'D. necessity'],
        correct_answer: 'C. necessary',
    },
    {
        questionNumber: '12',
        question: '_____ that the insulation has been replaced, the building is much more energy-efficient.',
        options: ['A. Now', 'B. For', 'C. As', 'D. Though'],
        correct_answer: 'A. Now',
    },
    {
        questionNumber: '13',
        question: 'Mr. Sims needs a more _____ vehicle for commuting from his suburban home to his office downtown.',
        options: ['A. expressive', 'B. reliable', 'C. partial', 'D. extreme'],
        correct_answer: 'B. reliable',
    },
    {
        questionNumber: '14',
        question: 'The company _____ lowered its prices to outsell its competitors and attract more customers.',
        options: ['A. strategy', 'B. strategically', 'C. strategies', 'D. strategic'],
        correct_answer: 'D. strategic',
    },
    {
        questionNumber: '15',
        question:
            '_____ Mr. Williams addressed the audience, he showed a brief video about the engine he had designed.',
        options: ['A. Then', 'B. So that', 'C. Before', 'D. Whereas'],
        correct_answer: 'C. Before',
    },
    {
        questionNumber: '16',
        question: 'For optimal safety on the road, avoid _____ the view of the rear window and side-view mirrors.',
        options: ['A. obstructs', 'B. obstructed', 'C. obstruction', 'D. obstructing'],
        correct_answer: 'D. obstructing',
    },
    {
        questionNumber: '17',
        question:
            'Having proper ventilation throughout the building is _____ for protecting the health and well-being of the workers.',
        options: ['A. cooperative', 'B. visible', 'C. essential', 'D. alternative'],
        correct_answer: 'C. essential',
    },
    {
        questionNumber: '18',
        question:
            '_____ sales of junk food have been steadily declining indicates that consumers are becoming more health-conscious.',
        options: ['A. In addition to', 'B. The fact that', 'C. As long as', 'D. In keeping with'],
        correct_answer: 'B. The fact that',
    },
    {
        questionNumber: '19',
        question: "The sprinklers for the lawn's irrigation system are _____ controlled.",
        options: ['A. mechanically', 'B. mechanic', 'C. mechanism', 'D. mechanical'],
        correct_answer: 'A. mechanically',
    },
    {
        questionNumber: '20',
        question: 'The library staff posted signs to _____ patrons of the upcoming closure for renovations.',
        options: ['A. notify', 'B. agree', 'C. generate', 'D. perform'],
        correct_answer: 'A. notify',
    },
    {
        questionNumber: '21',
        question:
            'Mr. Ross, _____ is repainting the interior of the lobby, was recommended by a friend of the building manager.',
        options: ['A. himself', 'B. he', 'C. who', 'D. which'],
        correct_answer: 'C. who',
    },
    {
        questionNumber: '22',
        question: 'The guidelines for the monthly publication are _____ revised to adapt to the changing readers.',
        options: ['A. courteously', 'B. initially', 'C. periodically', 'D. physically'],
        correct_answer: 'C. periodically',
    },
    {
        questionNumber: '23',
        question: '_____ an ankle injury, the baseball player participated in the last game of the season.',
        options: ['A. In spite of', 'B. Even if', 'C. Whether', 'D. Given that'],
        correct_answer: 'A. In spite of',
    },
    {
        questionNumber: '24',
        question: 'The governmental department used to provide financial aid, but now it offers _____ services only.',
        options: ['A. legal', 'B. legalize', 'C. legally', 'D. legalizes'],
        correct_answer: 'A. legal',
    },
    {
        questionNumber: '25',
        question: "At the guest's_____, an extra set of towels and complimentary soaps were brought to the room.",
        options: ['A. quote', 'B. graduation', 'C. request', 'D. dispute'],
        correct_answer: 'C. request',
    },
    {
        questionNumber: '26',
        question:
            "The upscale boutique Jane's Closet is known for selling the most stylish _____ for young professionals.",
        options: ['A. accessorized', 'B. accessorize', 'C. accessorizes', 'D. accessories'],
        correct_answer: 'D. accessories',
    },
    {
        questionNumber: '27',
        question: 'The company started recognize the increasing _____ of using resources responsibly.',
        options: ['A. more important', 'B. importantly', 'C. importance', 'D. important'],
        correct_answer: 'C. importance',
    },
    {
        questionNumber: '28',
        question:
            '_____ restructuring several departments within the company, the majority of the problems with miscommunication have disappeared.',
        options: ['A. After', 'B. Until', 'C. Below', 'D. Like'],
        correct_answer: 'A. After',
    },
    {
        questionNumber: '29',
        question: 'The riskiest _____ of the development of new medications are the trials with human subjects.',
        options: ['A. proceeds', 'B. perspectives', 'C. installments', 'D. stages'],
        correct_answer: 'D. stages',
    },
    {
        questionNumber: '30',
        question: '_____ seeking a position at Tulare Designs must submit a portfolio of previous work.',
        options: ['A. Anyone', 'B. Whenever', 'C. Other', 'D. Fewer'],
        correct_answer: 'A. Anyone',
    },
    {
        questionNumber: '31',
        question: '(31)',
        options: ['A. seek', 'B. to seek', 'C. seeking', 'D. are seeking'],
        correct_answer: 'C. seeking',
    },
    {
        questionNumber: '32',
        question: '(32)',
        options: ['A. extensive', 'B. restricted', 'C. generous', 'D. limitless'],
        correct_answer: 'A. extensive',
    },
    {
        questionNumber: '33',
        question: '(33)',
        options: [
            'A. I would really appreciate the opportunity to work with you.',
            'B. I heard that DigitalIT is a great company.',
            'C. In fact, our designs are often copied by other companies.',
            'D. I have attached a number of our past designs to illustrate what we specialize in.',
        ],
        correct_answer: 'D. I have attached a number of our past designs to illustrate what we specialize in.',
    },
    {
        questionNumber: '34',
        question: '(34)',
        options: ['A. at', 'B. to', 'C. with', 'D. from'],
        correct_answer: 'B. to',
    },
    {
        questionNumber: '35',
        question: '(35)',
        options: ['A. durable', 'B. durability', 'C. duration', 'D. during'],
        correct_answer: 'B. durability',
    },
    {
        questionNumber: '36',
        question: '(36)',
        options: [
            "A. Larson's utensils and silverware go great with the dinnerware.",
            'B. Our most popular line, the Spring Flower China is sold out at most locations.',
            'C. Visit our store to check out our other beautiful products.',
            "D. They are dishwasher- and microwave-safe and we're confident that you'll be using them for years to come.",
        ],
        correct_answer:
            "D. They are dishwasher- and microwave-safe and we're confident that you'll be using them for years to come.",
    },
    {
        questionNumber: '37',
        question: '(37)',
        options: ['A. result in', 'B. occur to', 'C. ending at', 'D. stop with'],
        correct_answer: 'A. result in',
    },
    {
        questionNumber: '38',
        question: '(38)',
        options: ['A. ambitious', 'B. combative', 'C. aggressive', 'D. complacent'],
        correct_answer: 'C. aggressive',
    },
    {
        questionNumber: '39',
        question: '(39)',
        options: ['A. account', 'B. accountant', 'C. accounting', 'D. accounted'],
        correct_answer: 'C. accounting',
    },
    {
        questionNumber: '40',
        question: '(40)',
        options: ['A. basic', 'B. decisive', 'C. additional', 'D. necessary'],
        correct_answer: 'D. necessary',
    },
    {
        questionNumber: '41',
        question: '(41)',
        options: ['A. is being', 'B. will be', 'C. has been', 'D. were being'],
        correct_answer: 'B. will be',
    },
    {
        questionNumber: '42',
        question: '(42)',
        options: [
            'A. We sincerely thank you for your interest.',
            'B. The positions begin the following month.',
            'C. Please call us for more information.',
            'D. We apologize for any inconvenience.',
        ],
        correct_answer: 'B. The positions begin the following month.',
    },
    {
        questionNumber: '43',
        question: '(43)',
        options: ['A. are bringing in', 'B. have brought in', 'C. bring in', 'D. are brought in'],
        correct_answer: 'D. are brought in',
    },
    {
        questionNumber: '44',
        question: '(44)',
        options: [
            'A. This will take a lot of work.',
            'B. As a result, the convenience shops will be closed.',
            'C. Because of this, hot meals will not be available for the patrons.',
            'D. There will be noise and chaos as a result.',
        ],
        correct_answer: 'C. Because of this, hot meals will not be available for the patrons.',
    },
    {
        questionNumber: '45',
        question: '(45)',
        options: ['A. before', 'B. after', 'C. during', 'D. within'],
        correct_answer: 'C. during',
    },
    {
        questionNumber: '46',
        question: '(46)',
        options: ['A. develop', 'B. improve', 'C. rectify', 'D. recover'],
        correct_answer: 'B. improve',
    },
    {
        questionNumber: '47',
        question: 'What is the purpose of the announcement?',
        options: [
            'A. To celebrate a new product release',
            'B. To inform about a new service',
            'C. To discuss an internal policy change',
            'D. To introduce a new staff member',
        ],
        correct_answer: 'B. To inform about a new service',
    },
    {
        questionNumber: '48',
        question: 'According to the advertisement, what is offered to customers?',
        options: [
            'A. A discount on a new product',
            'B. A gift with purchase',
            'C. A free trial of a service',
            'D. Free membership for a year',
        ],
        correct_answer: 'A. A discount on a new product',
    },
    {
        questionNumber: '49',
        question: 'Why are the team members in the meeting discussing this project?',
        options: [
            'A. To evaluate progress',
            'B. To plan the next phase',
            'C. To select a leader',
            'D. To finalize the budget',
        ],
        correct_answer: 'B. To plan the next phase',
    },
    {
        questionNumber: '50',
        question: "What is the most likely reason for the company's decision?",
        options: [
            'A. To improve efficiency',
            'B. To increase employee morale',
            'C. To save costs',
            'D. To follow industry trends',
        ],
        correct_answer: 'C. To save costs',
    },
    {
        questionNumber: '51',
        question: 'What is the main focus of the seminar?',
        options: [
            'A. Effective communication strategies',
            'B. Financial planning for startups',
            'C. Marketing techniques for social media',
            'D. Leadership and team building',
        ],
        correct_answer: 'D. Leadership and team building',
    },
    {
        questionNumber: '52',
        question: 'What is recommended by the company for better results?',
        options: [
            'A. Hiring more staff',
            'B. Updating the software regularly',
            'C. Implementing new marketing strategies',
            'D. Conducting additional training',
        ],
        correct_answer: 'B. Updating the software regularly',
    },
    {
        questionNumber: '53',
        question: 'What is the company offering for long-term clients?',
        options: [
            'A. Extra services at no charge',
            'B. A special loyalty bonus',
            'C. A limited edition product',
            'D. A free upgrade to premium membership',
        ],
        correct_answer: 'B. A special loyalty bonus',
    },
    {
        questionNumber: '54',
        question: 'What is the primary concern of the client?',
        options: [
            'A. Quality of customer support',
            'B. Delivery time for products',
            'C. Product pricing',
            'D. Warranty terms',
        ],
        correct_answer: 'B. Delivery time for products',
    },
    {
        questionNumber: '55',
        question: 'What is the client most likely to do next?',
        options: [
            'A. Submit the proposal for approval',
            'B. Contact customer support for assistance',
            'C. Make an online purchase',
            'D. Request a demonstration of the product',
        ],
        correct_answer: 'D. Request a demonstration of the product',
    },
    {
        questionNumber: '56',
        question: 'What can be inferred about the marketing team?',
        options: [
            "A. They are responsible for the company's financial planning",
            'B. They are exploring new ways to increase customer engagement',
            'C. They are in charge of all product development',
            "D. They are focused on maintaining the company's current market position",
        ],
        correct_answer: 'B. They are exploring new ways to increase customer engagement',
    },
    {
        questionNumber: '57',
        question: "What is suggested by the company's new strategy?",
        options: [
            'A. A shift to more eco-friendly products',
            'B. A move to international markets',
            'C. A focus on customer retention',
            'D. A reduction in production costs',
        ],
        correct_answer: 'C. A focus on customer retention',
    },
    {
        questionNumber: '58',
        question: 'What is the outcome of the recent changes?',
        options: [
            'A. Increased production output',
            'B. Improved customer satisfaction',
            'C. Decreased employee turnover',
            'D. Expanded product lines',
        ],
        correct_answer: 'B. Improved customer satisfaction',
    },
    {
        questionNumber: '59',
        question: 'What was the reason for the delay in the project?',
        options: [
            'A. Supply chain disruptions',
            'B. Internal communication issues',
            'C. Unexpected market changes',
            'D. Lack of resources',
        ],
        correct_answer: 'A. Supply chain disruptions',
    },
    {
        questionNumber: '60',
        question: 'What did the customer most appreciate about the service?',
        options: [
            'A. The fast delivery time',
            'B. The friendly customer support',
            'C. The low prices',
            'D. The easy-to-use website',
        ],
        correct_answer: 'B. The friendly customer support',
    },
    {
        questionNumber: '61',
        question: 'What is the target audience for the new campaign?',
        options: [
            'A. Senior citizens',
            'B. Young professionals',
            'C. College students',
            'D. Parents with young children',
        ],
        correct_answer: 'B. Young professionals',
    },
    {
        questionNumber: '62',
        question: 'What feature of the product is highlighted in the advertisement?',
        options: ['A. Its affordability', 'B. Its ease of use', 'C. Its sleek design', 'D. Its long battery life'],
        correct_answer: 'B. Its ease of use',
    },
    {
        questionNumber: '63',
        question: 'Why did the company decide to extend its hours of operation?',
        options: [
            'A. To accommodate more customers',
            'B. To provide better service to existing clients',
            'C. To improve employee satisfaction',
            'D. To comply with government regulations',
        ],
        correct_answer: 'A. To accommodate more customers',
    },
    {
        questionNumber: '64',
        question: 'What is the main objective of the new policy?',
        options: [
            'A. To reduce operational costs',
            'B. To increase transparency',
            'C. To improve employee benefits',
            'D. To enhance customer experience',
        ],
        correct_answer: 'B. To increase transparency',
    },
    {
        questionNumber: '65',
        question: 'What is the expected result of implementing the new software?',
        options: [
            'A. Faster decision-making',
            'B. Improved security measures',
            'C. Increased market share',
            'D. Better employee communication',
        ],
        correct_answer: 'D. Better employee communication',
    },
    {
        questionNumber: '66',
        question: 'What is likely to be the next step for the team?',
        options: [
            'A. Begin production',
            'B. Present the proposal to the board',
            'C. Conduct additional research',
            'D. Finalize the budget',
        ],
        correct_answer: 'C. Conduct additional research',
    },
    {
        questionNumber: '67',
        question: 'Why was the meeting postponed?',
        options: [
            'A. The main speaker was unavailable',
            'B. There was a scheduling conflict',
            'C. The presentation was not ready',
            'D. The venue was unavailable',
        ],
        correct_answer: 'B. There was a scheduling conflict',
    },
    {
        questionNumber: '68',
        question: 'What would be the best way to resolve the issue mentioned?',
        options: [
            'A. By implementing a new policy',
            'B. By providing additional training',
            'C. By offering a discount',
            'D. By changing suppliers',
        ],
        correct_answer: 'B. By providing additional training',
    },
    {
        questionNumber: '69',
        question: 'What does the client want to know about the product?',
        options: ['A. Its price', 'B. Its functionality', 'C. Its availability', 'D. Its warranty period'],
        correct_answer: 'B. Its functionality',
    },
    {
        questionNumber: '70',
        question: 'What did the team achieve by the end of the quarter?',
        options: [
            'A. A significant increase in sales',
            'B. Improved customer feedback',
            'C. Completion of a major project',
            'D. An expansion of the product line',
        ],
        correct_answer: 'C. Completion of a major project',
    },
    {
        questionNumber: '71',
        question: 'What can be found on the Association of Web Designers website?',
        options: [
            'A. A transcript of a speech',
            'B. An application for an open position',
            'C. Details about upcoming contests',
            "D. A list of Ms. Holt's accomplishments",
        ],
        correct_answer: 'C. Details about upcoming contests',
    },
    {
        questionNumber: '72',
        question: 'What is suggested about the shop?',
        options: [
            'A. It is very successful.',
            'B. It only offers take-out.',
            'C. It has been open for a long time.',
            'D. Only fitness experts patron the shop.',
        ],
        correct_answer: 'A. It is very successful.',
    },
    {
        questionNumber: '73',
        question: 'What is suggested about Health Shack products?',
        options: [
            'A. They are very delicious.',
            'B. They are healthy.',
            'C. They are cheap.',
            'D. They are easy to get.',
        ],
        correct_answer: 'B. They are healthy.',
    },
    {
        questionNumber: '74',
        question: "Why don't the owners advertise?",
        options: [
            "A. They don't have enough money.",
            'B. They are too busy.',
            'C. Their customers recommend the place to others.',
            "D. They don't want to.",
        ],
        correct_answer: 'C. Their customers recommend the place to others.',
    },
    {
        questionNumber: '75',
        question:
            "In which of the positions marked [1], [2], [3], and [4] does the following sentence belong? 'Despite the limited number of products on the menu, customers can't get enough of the tasty but healthy shakes that are on offer.'",
        options: ['A. [1]', 'B. [2]', 'C. [3]', 'D. [4]'],
        correct_answer: 'B. [2]',
    },
    {
        questionNumber: '76',
        question: 'Who most likely is the lecture series intended for?',
        options: [
            'A. Community members',
            'B. Building superintendents',
            'C. University professors',
            'D. Hospital patients',
        ],
        correct_answer: 'C. University professors',
    },
    {
        questionNumber: '77',
        question: "In the brochure, the word 'through' is closest in meaning to",
        options: ['A. over', 'B. via', 'C. across', 'D. until'],
        correct_answer: 'B. via',
    },
    {
        questionNumber: '78',
        question: 'What most likely will be discussed at the lecture on February 10?',
        options: [
            'A. How to balance yearly budgets',
            'B. How to meet infrastructure needs',
            'C. How to avoid environmental damage',
            'D. How to stimulate economic development',
        ],
        correct_answer: 'D. How to stimulate economic development',
    },
    {
        questionNumber: '79',
        question: 'According to Mr. Patterson, whose lecture must be rescheduled?',
        options: ["A. Mr. Watson's", "B. Mr. Ross's", "C. Ms. Simmons's", "D. Mr. Powell's"],
        correct_answer: "A. Mr. Watson's",
    },
    {
        questionNumber: '80',
        question: 'What is Ms. Flores instructed to do on a website?',
        options: [
            'A. Download a document',
            'B. Change a room reservation',
            'C. Update personal information',
            'D. Facilitate a forum',
        ],
        correct_answer: 'C. Update personal information',
    },
    {
        questionNumber: '81',
        question: 'What can be inferred about Ms. Russell?',
        options: [
            "A. She is Ms. Bennett's co-worker.",
            'B. She is planning a honeymoon.',
            'C. She is currently engaged.',
            'D. She works for a catering company.',
        ],
        correct_answer: 'C. She is currently engaged.',
    },
    {
        questionNumber: '82',
        question: 'Who most likely is Ms. Bennett?',
        options: [
            'A. A professional musician',
            'B. A wedding photographer',
            'C. An interior designer',
            'D. An event planner',
        ],
        correct_answer: 'D. An event planner',
    },
    {
        questionNumber: '83',
        question: 'What is suggested about all the locations on the list?',
        options: [
            'A. They are close to a main road.',
            'B. They are indoor venues.',
            'C. They are located in the same city.',
            'D. They require a down payment.',
        ],
        correct_answer: 'C. They are located in the same city.',
    },
    {
        questionNumber: '84',
        question: 'What information is Ms. Russell asked to provide?',
        options: ['A. A potential date', 'B. A meal selection', 'C. A list of guests', 'D. A meeting location'],
        correct_answer: 'C. A list of guests',
    },
    {
        questionNumber: '85',
        question: "What package would probably best suit Ms. Russell's needs?",
        options: ['A. Diamond', 'B. Emerald', 'C. Ruby', 'D. Sapphire'],
        correct_answer: 'B. Emerald',
    },
    {
        questionNumber: '86',
        question: 'What is the purpose of the first e-mail?',
        options: [
            'A. To request cost information',
            'B. To inquire about a policy change',
            'C. To postpone an order',
            'D. To report an incorrect invoice',
        ],
        correct_answer: 'C. To postpone an order',
    },
    {
        questionNumber: '87',
        question: "What package option most likely fits Ms. Hall's needs best?",
        options: ['A. Personal', 'B. Small', 'C. Medium', 'D. Large'],
        correct_answer: 'C. Medium',
    },
    {
        questionNumber: '88',
        question: 'What information is not needed for a final price?',
        options: ['A. Length of contract', 'B. Method of delivery', 'C. Additional items', 'D. Distance of shipping'],
        correct_answer: 'D. Distance of shipping',
    },
    {
        questionNumber: '89',
        question: "What is indicated in Emily Hall's e-mail?",
        options: [
            'A. She wants to try it for a month.',
            'B. She wants the free gift.',
            'C. She is interested in a long-term contract.',
            "D. She doesn't want winter produce.",
        ],
        correct_answer: 'C. She is interested in a long-term contract.',
    },
    {
        questionNumber: '90',
        question: 'Why does Emily Hall want to know about the vegetables that will be available throughout the year?',
        options: [
            'A. She loves vegetables.',
            'B. She is thinking about adding meat.',
            'C. She might hire another employee.',
            'D. She wants to plan her future menus.',
        ],
        correct_answer: 'D. She wants to plan her future menus.',
    },
    {
        questionNumber: '91',
        question: 'Where would the notice most likely be found?',
        options: ['A. In a restaurant', 'B. In a staff break room', 'C. In a shipping agency', 'D. In a grocery store'],
        correct_answer: 'B. In a staff break room',
    },
    {
        questionNumber: '92',
        question: 'What is indicated about the jars?',
        options: [
            'A. They were not closed tightly.',
            'B. They are currently out of stock.',
            'C. They were priced incorrectly.',
            'D. They were delivered to the wrong address.',
        ],
        correct_answer: 'A. They were not closed tightly.',
    },
    {
        questionNumber: '93',
        question: 'According to the notice, what is NOT mentioned as advice for customers?',
        options: [
            'A. Avoiding consuming the product',
            'B. Reporting on the product',
            'C. Returning the product to a store',
            'D. Purchasing other Castelli products',
        ],
        correct_answer: 'D. Purchasing other Castelli products',
    },
    {
        questionNumber: '94',
        question: 'In the e-mail to Mr. Hester, what additional gift does Castelli offer?',
        options: ['A. Pasta sauce', 'B. A recipe book', 'C. Vouchers for produce', 'D. Vouchers for new products'],
        correct_answer: 'B. A recipe book',
    },
    {
        questionNumber: '95',
        question: 'Castelli is sending the vouchers for several reasons; what is NOT one of them?',
        options: [
            'A. To keep customers loyal',
            'B. To say that they were sorry',
            'C. To be fair to their customers',
            'D. To gain new customers',
        ],
        correct_answer: 'D. To gain new customers',
    },
    {
        questionNumber: '96',
        question: 'Why was the inspection conducted?',
        options: [
            'A. To monitor compliance with food industry regulations',
            'B. To rate the taste and quality of the cuisine',
            'C. To inspect the structural safety of the building',
            'D. To evaluate the effectiveness of new policies',
        ],
        correct_answer: 'A. To monitor compliance with food industry regulations',
    },
    {
        questionNumber: '97',
        question: "Why has Polito's Pizza been charged a fine?",
        options: [
            'A. Because fire extinguishers were not in place.',
            'B. Because containers of food were not marked appropriately.',
            'C. Because raw meats and vegetables were handled incorrectly.',
            'D. Because the facilities were not cleaned according to standards.',
        ],
        correct_answer: 'B. Because containers of food were not marked appropriately.',
    },
    {
        questionNumber: '98',
        question: 'What does Mr. Kluck ask his employees to do?',
        options: [
            'A. Apologize to customers',
            'B. Wear a name tag at all times',
            'C. File a complaint with Ms. Tenner',
            'D. Fill out a required form',
        ],
        correct_answer: 'B. Wear a name tag at all times',
    },
    {
        questionNumber: '99',
        question: 'What will happen if an employee fails to sign the work checklist?',
        options: [
            'A. They will have a violation on their record.',
            'B. They will have to pay a fine.',
            'C. They will have to come in on the weekends.',
            'D. They will be fired.',
        ],
        correct_answer: 'A. They will have a violation on their record.',
    },
    {
        questionNumber: '100',
        question: "Based on Polito's Checklist, what can we infer about K.P.?",
        options: [
            'A. He works at night.',
            'B. He did not work on Thursday and Friday.',
            'C. He will be fired for violations.',
            'D. He is slow at work.',
        ],
        correct_answer: 'B. He did not work on Thursday and Friday.',
    },
];
