export const questions_01_02 = [
    {
        id: '47',
        questionNumber: '47',
        question: 'What is the purpose of the announcement?',
        options: [
            { label: 'A. To celebrate a new product release', value: 'A' },
            { label: 'B. To inform about a new service', value: 'B' },
            { label: 'C. To discuss an internal policy change', value: 'C' },
            { label: 'D. To introduce a new staff member', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '48',
        questionNumber: '48',
        question: 'According to the advertisement, what is offered to customers?',
        options: [
            { label: 'A. A discount on a new product', value: 'A' },
            { label: 'B. A gift with purchase', value: 'B' },
            { label: 'C. A free trial of a service', value: 'C' },
            { label: 'D. Free membership for a year', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '49',
        questionNumber: '49',
        question: 'Why are the team members in the meeting discussing this project?',
        options: [
            { label: 'A. To evaluate progress', value: 'A' },
            { label: 'B. To plan the next phase', value: 'B' },
            { label: 'C. To select a leader', value: 'C' },
            { label: 'D. To finalize the budget', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '50',
        questionNumber: '50',
        question: "What is the most likely reason for the company's decision?",
        options: [
            { label: 'A. To improve efficiency', value: 'A' },
            { label: 'B. To increase employee morale', value: 'B' },
            { label: 'C. To save costs', value: 'C' },
            { label: 'D. To follow industry trends', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '51',
        questionNumber: '51',
        question: 'What is the main focus of the seminar?',
        options: [
            { label: 'A. Effective communication strategies', value: 'A' },
            { label: 'B. Financial planning for startups', value: 'B' },
            { label: 'C. Marketing techniques for social media', value: 'C' },
            { label: 'D. Leadership and team building', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '52',
        questionNumber: '52',
        question: 'What is recommended by the company for better results?',
        options: [
            { label: 'A. Hiring more staff', value: 'A' },
            { label: 'B. Updating the software regularly', value: 'B' },
            { label: 'C. Implementing new marketing strategies', value: 'C' },
            { label: 'D. Conducting additional training', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '53',
        questionNumber: '53',
        question: 'What is the company offering for long-term clients?',
        options: [
            { label: 'A. Extra services at no charge', value: 'A' },
            { label: 'B. A special loyalty bonus', value: 'B' },
            { label: 'C. A limited edition product', value: 'C' },
            { label: 'D. A free upgrade to premium membership', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '54',
        questionNumber: '54',
        question: 'What is the primary concern of the client?',
        options: [
            { label: 'A. Quality of customer support', value: 'A' },
            { label: 'B. Delivery time for products', value: 'B' },
            { label: 'C. Product pricing', value: 'C' },
            { label: 'D. Warranty terms', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '55',
        questionNumber: '55',
        question: 'What is the client most likely to do next?',
        options: [
            { label: 'A. Submit the proposal for approval', value: 'A' },
            { label: 'B. Contact customer support for assistance', value: 'B' },
            { label: 'C. Make an online purchase', value: 'C' },
            { label: 'D. Request a demonstration of the product', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '56',
        questionNumber: '56',
        question: 'What can be inferred about the marketing team?',
        options: [
            { label: "A. They are responsible for the company's financial planning", value: 'A' },
            { label: 'B. They are exploring new ways to increase customer engagement', value: 'B' },
            { label: 'C. They are in charge of all product development', value: 'C' },
            { label: "D. They are focused on maintaining the company's current market position", value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '57',
        questionNumber: '57',
        question: "What is suggested by the company's new strategy?",
        options: [
            { label: 'A. A shift to more eco-friendly products', value: 'A' },
            { label: 'B. A move to international markets', value: 'B' },
            { label: 'C. A focus on customer retention', value: 'C' },
            { label: 'D. A reduction in production costs', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '58',
        questionNumber: '58',
        question: 'What is the outcome of the recent changes?',
        options: [
            { label: 'A. Increased production output', value: 'A' },
            { label: 'B. Improved customer satisfaction', value: 'B' },
            { label: 'C. Decreased employee turnover', value: 'C' },
            { label: 'D. Expanded product lines', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '59',
        questionNumber: '59',
        question: 'What was the reason for the delay in the project?',
        options: [
            { label: 'A. Supply chain disruptions', value: 'A' },
            { label: 'B. Internal communication issues', value: 'B' },
            { label: 'C. Unexpected market changes', value: 'C' },
            { label: 'D. Lack of resources', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '60',
        questionNumber: '60',
        question: 'What did the customer most appreciate about the service?',
        options: [
            { label: 'A. The fast delivery time', value: 'A' },
            { label: 'B. The friendly customer support', value: 'B' },
            { label: 'C. The low prices', value: 'C' },
            { label: 'D. The easy-to-use website', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '61',
        questionNumber: '61',
        question: 'What is the target audience for the new campaign?',
        options: [
            { label: 'A. Senior citizens', value: 'A' },
            { label: 'B. Young professionals', value: 'B' },
            { label: 'C. College students', value: 'C' },
            { label: 'D. Parents with young children', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '62',
        questionNumber: '62',
        question: 'What feature of the product is highlighted in the advertisement?',
        options: [
            { label: 'A. Its affordability', value: 'A' },
            { label: 'B. Its ease of use', value: 'B' },
            { label: 'C. Its sleek design', value: 'C' },
            { label: 'D. Its long battery life', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '63',
        questionNumber: '63',
        question: 'Why did the company decide to extend its hours of operation?',
        options: [
            { label: 'A. To accommodate more customers', value: 'A' },
            { label: 'B. To provide better service to existing clients', value: 'B' },
            { label: 'C. To improve employee satisfaction', value: 'C' },
            { label: 'D. To comply with government regulations', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '64',
        questionNumber: '64',
        question: 'What is the main objective of the new policy?',
        options: [
            { label: 'A. To reduce operational costs', value: 'A' },
            { label: 'B. To increase transparency', value: 'B' },
            { label: 'C. To improve employee benefits', value: 'C' },
            { label: 'D. To enhance customer experience', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '65',
        questionNumber: '65',
        question: 'What is the expected result of implementing the new software?',
        options: [
            { label: 'A. Faster decision-making', value: 'A' },
            { label: 'B. Improved security measures', value: 'B' },
            { label: 'C. Increased market share', value: 'C' },
            { label: 'D. Better employee communication', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '66',
        questionNumber: '66',
        question: 'What is likely to be the next step for the team?',
        options: [
            { label: 'A. Begin production', value: 'A' },
            { label: 'B. Present the proposal to the board', value: 'B' },
            { label: 'C. Conduct additional research', value: 'C' },
            { label: 'D. Finalize the budget', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '67',
        questionNumber: '67',
        question: 'Why was the meeting postponed?',
        options: [
            { label: 'A. The main speaker was unavailable', value: 'A' },
            { label: 'B. There was a scheduling conflict', value: 'B' },
            { label: 'C. The presentation was not ready', value: 'C' },
            { label: 'D. The venue was unavailable', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '68',
        questionNumber: '68',
        question: 'What would be the best way to resolve the issue mentioned?',
        options: [
            { label: 'A. By implementing a new policy', value: 'A' },
            { label: 'B. By providing additional training', value: 'B' },
            { label: 'C. By offering a discount', value: 'C' },
            { label: 'D. By changing suppliers', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '69',
        questionNumber: '69',
        question: 'What does the client want to know about the product?',
        options: [
            { label: 'A. Its price', value: 'A' },
            { label: 'B. Its functionality', value: 'B' },
            { label: 'C. Its availability', value: 'C' },
            { label: 'D. Its warranty period', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '70',
        questionNumber: '70',
        question: 'What did the team achieve by the end of the quarter?',
        options: [
            { label: 'A. A significant increase in sales', value: 'A' },
            { label: 'B. Improved customer feedback', value: 'B' },
            { label: 'C. Completion of a major project', value: 'C' },
            { label: 'D. An expansion of the product line', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '71',
        questionNumber: '71',
        question: 'What can be found on the Association of Web Designers website?',
        options: [
            { label: 'A. A transcript of a speech', value: 'A' },
            { label: 'B. An application for an open position', value: 'B' },
            { label: 'C. Details about upcoming contests', value: 'C' },
            { label: "D. A list of Ms. Holt's accomplishments", value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '72',
        questionNumber: '72',
        question: 'What is suggested about the shop?',
        options: [
            { label: 'A. It is very successful.', value: 'A' },
            { label: 'B. It only offers take-out.', value: 'B' },
            { label: 'C. It has been open for a long time.', value: 'C' },
            { label: 'D. Only fitness experts patron the shop.', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '73',
        questionNumber: '73',
        question: 'What is suggested about Health Shack products?',
        options: [
            { label: 'A. They are very delicious.', value: 'A' },
            { label: 'B. They are healthy.', value: 'B' },
            { label: 'C. They are cheap.', value: 'C' },
            { label: 'D. They are easy to get.', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '74',
        questionNumber: '74',
        question: "Why don't the owners advertise?",
        options: [
            { label: "A. They don't have enough money.", value: 'A' },
            { label: 'B. They are too busy.', value: 'B' },
            { label: 'C. Their customers recommend the place to others.', value: 'C' },
            { label: "D. They don't want to.", value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '75',
        questionNumber: '75',
        question:
            'In which of the positions marked [1], [2], [3], and [4] does the following sentence belong? "Despite the limited number of products on the menu, customers can\'t get enough of the tasty but healthy shakes that are on offer."',
        options: [
            { label: 'A. [1]', value: 'A' },
            { label: 'B. [2]', value: 'B' },
            { label: 'C. [3]', value: 'C' },
            { label: 'D. [4]', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '76',
        questionNumber: '76',
        question: 'Who most likely is the lecture series intended for?',
        options: [
            { label: 'A. Community members', value: 'A' },
            { label: 'B. Building superintendents', value: 'B' },
            { label: 'C. University professors', value: 'C' },
            { label: 'D. Hospital patients', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '77',
        questionNumber: '77',
        question: 'In the brochure, the word "through" is closest in meaning to',
        options: [
            { label: 'A. over', value: 'A' },
            { label: 'B. via', value: 'B' },
            { label: 'C. across', value: 'C' },
            { label: 'D. until', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '78',
        questionNumber: '78',
        question: 'What most likely will be discussed at the lecture on February 10?',
        options: [
            { label: 'A. How to balance yearly budgets', value: 'A' },
            { label: 'B. How to meet infrastructure needs', value: 'B' },
            { label: 'C. How to avoid environmental damage', value: 'C' },
            { label: 'D. How to stimulate economic development', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '79',
        questionNumber: '79',
        question: 'According to Mr. Patterson, whose lecture must be rescheduled?',
        options: [
            { label: "A. Mr. Watson's", value: 'A' },
            { label: "B. Mr. Ross's", value: 'B' },
            { label: "C. Ms. Simmons's", value: 'C' },
            { label: "D. Mr. Powell's", value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '80',
        questionNumber: '80',
        question: 'What is Ms. Flores instructed to do on a website?',
        options: [
            { label: 'A. Download a document', value: 'A' },
            { label: 'B. Change a room reservation', value: 'B' },
            { label: 'C. Update personal information', value: 'C' },
            { label: 'D. Facilitate a forum', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '81',
        questionNumber: '81',
        question: 'What can be inferred about Ms. Russell?',
        options: [
            { label: "A. She is Ms. Bennett's co-worker.", value: 'A' },
            { label: 'B. She is planning a honeymoon.', value: 'B' },
            { label: 'C. She is currently engaged.', value: 'C' },
            { label: 'D. She works for a catering company.', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '82',
        questionNumber: '82',
        question: 'Who most likely is Ms. Bennett?',
        options: [
            { label: 'A. A professional musician', value: 'A' },
            { label: 'B. A wedding photographer', value: 'B' },
            { label: 'C. An interior designer', value: 'C' },
            { label: 'D. An event planner', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '83',
        questionNumber: '83',
        question: 'What is suggested about all the locations on the list?',
        options: [
            { label: 'A. They are close to a main road.', value: 'A' },
            { label: 'B. They are indoor venues.', value: 'B' },
            { label: 'C. They are located in the same city.', value: 'C' },
            { label: 'D. They require a down payment.', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '84',
        questionNumber: '84',
        question: 'What information is Ms. Russell asked to provide?',
        options: [
            { label: 'A. A potential date', value: 'A' },
            { label: 'B. A meal selection', value: 'B' },
            { label: 'C. A list of guests', value: 'C' },
            { label: 'D. A meeting location', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '85',
        questionNumber: '85',
        question: "What package would probably best suit Ms. Russell's needs?",
        options: [
            { label: 'A. Diamond', value: 'A' },
            { label: 'B. Emerald', value: 'B' },
            { label: 'C. Ruby', value: 'C' },
            { label: 'D. Sapphire', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '86',
        questionNumber: '86',
        question: 'What is the purpose of the first e-mail?',
        options: [
            { label: 'A. To request cost information', value: 'A' },
            { label: 'B. To inquire about a policy change', value: 'B' },
            { label: 'C. To postpone an order', value: 'C' },
            { label: 'D. To report an incorrect invoice', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '87',
        questionNumber: '87',
        question: "What package option most likely fits Ms. Hall's needs best?",
        options: [
            { label: 'A. Personal', value: 'A' },
            { label: 'B. Small', value: 'B' },
            { label: 'C. Medium', value: 'C' },
            { label: 'D. Large', value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '88',
        questionNumber: '88',
        question: 'What information is not needed for a final price?',
        options: [
            { label: 'A. Length of contract', value: 'A' },
            { label: 'B. Method of delivery', value: 'B' },
            { label: 'C. Additional items', value: 'C' },
            { label: 'D. Distance of shipping', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '89',
        questionNumber: '89',
        question: "What is indicated in Emily Hall's e-mail?",
        options: [
            { label: 'A. She wants to try it for a month.', value: 'A' },
            { label: 'B. She wants the free gift.', value: 'B' },
            { label: 'C. She is interested in a long-term contract.', value: 'C' },
            { label: "D. She doesn't want winter produce.", value: 'D' },
        ],
        correct_answer: 'C',
    },
    {
        id: '90',
        questionNumber: '90',
        question: 'Why does Emily Hall want to know about the vegetables that will be available throughout the year?',
        options: [
            { label: 'A. She loves vegetables.', value: 'A' },
            { label: 'B. She is thinking about adding meat.', value: 'B' },
            { label: 'C. She might hire another employee.', value: 'C' },
            { label: 'D. She wants to plan her future menus.', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '91',
        questionNumber: '91',
        question: 'Where would the notice most likely be found?',
        options: [
            { label: 'A. In a restaurant', value: 'A' },
            { label: 'B. In a staff break room', value: 'B' },
            { label: 'C. In a shipping agency', value: 'C' },
            { label: 'D. In a grocery store', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '92',
        questionNumber: '92',
        question: 'What is indicated about the jars?',
        options: [
            { label: 'A. They were not closed tightly.', value: 'A' },
            { label: 'B. They are currently out of stock.', value: 'B' },
            { label: 'C. They were priced incorrectly.', value: 'C' },
            { label: 'D. They were delivered to the wrong address.', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '93',
        questionNumber: '93',
        question: 'According to the notice, what is NOT mentioned as advice for customers?',
        options: [
            { label: 'A. Avoiding consuming the product', value: 'A' },
            { label: 'B. Reporting on the product', value: 'B' },
            { label: 'C. Returning the product to a store', value: 'C' },
            { label: 'D. Purchasing other Castelli products', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '94',
        questionNumber: '94',
        question: 'In the e-mail to Mr. Hester, what additional gift does Castelli offer?',
        options: [
            { label: 'A. Pasta sauce', value: 'A' },
            { label: 'B. A recipe book', value: 'B' },
            { label: 'C. Vouchers for produce', value: 'C' },
            { label: 'D. Vouchers for new products', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '95',
        questionNumber: '95',
        question: 'Castelli is sending the vouchers for several reasons; what is NOT one of them?',
        options: [
            { label: 'A. To keep customers loyal', value: 'A' },
            { label: 'B. To say that they were sorry', value: 'B' },
            { label: 'C. To be fair to their customers', value: 'C' },
            { label: 'D. To gain new customers', value: 'D' },
        ],
        correct_answer: 'D',
    },
    {
        id: '96',
        questionNumber: '96',
        question: 'Why was the inspection conducted?',
        options: [
            { label: 'A. To monitor compliance with food industry regulations', value: 'A' },
            { label: 'B. To rate the taste and quality of the cuisine', value: 'B' },
            { label: 'C. To inspect the structural safety of the building', value: 'C' },
            { label: 'D. To evaluate the effectiveness of new policies', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '97',
        questionNumber: '97',
        question: "Why has Polito's Pizza been charged a fine?",
        options: [
            { label: 'A. Because fire extinguishers were not in place.', value: 'A' },
            { label: 'B. Because containers of food were not marked appropriately.', value: 'B' },
            { label: 'C. Because raw meats and vegetables were handled incorrectly.', value: 'C' },
            { label: 'D. Because the facilities were not cleaned according to standards.', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '98',
        questionNumber: '98',
        question: 'What does Mr. Kluck ask his employees to do?',
        options: [
            { label: 'A. Apologize to customers', value: 'A' },
            { label: 'B. Wear a name tag at all times', value: 'B' },
            { label: 'C. File a complaint with Ms. Tenner', value: 'C' },
            { label: 'D. Fill out a required form', value: 'D' },
        ],
        correct_answer: 'B',
    },
    {
        id: '99',
        questionNumber: '99',
        question: 'What will happen if an employee fails to sign the work checklist?',
        options: [
            { label: 'A. They will have a violation on their record.', value: 'A' },
            { label: 'B. They will have to pay a fine.', value: 'B' },
            { label: 'C. They will have to come in on the weekends.', value: 'C' },
            { label: 'D. They will be fired.', value: 'D' },
        ],
        correct_answer: 'A',
    },
    {
        id: '100',
        questionNumber: '100',
        question: "Based on Polito's Checklist, what can we infer about K.P.?",
        options: [
            { label: 'A. He works at night.', value: 'A' },
            { label: 'B. He did not work on Thursday and Friday.', value: 'B' },
            { label: 'C. He will be fired for violations.', value: 'C' },
            { label: 'D. He is slow at work.', value: 'D' },
        ],
        correct_answer: 'B',
    },
];
